-- Semantic layer — layer 3: speech_chunks + embeddings.
--
-- This is the table the retrieval pipeline queries. One row per
-- retrievable unit of text; a speech produces 1..N chunks.
--
-- Chunking rules (enforced by the ingester, not the schema):
--   • Default: one speaker turn → one chunk.
--   • If turn > 512 BGE-M3 tokens, split at paragraph boundary with a
--     50-token overlap; carry the same politician_id / metadata onto
--     every resulting chunk.
--   • Sub-20-token turns (procedural "Mr. Speaker", points of order)
--     stay on `speeches` but never chunk — they pollute retrieval.
--
-- Denormalised columns (politician_id, party_at_time, level,
-- province_territory, spoken_at, session_id) are copies of the parent
-- speech's values. They live here so WHERE-clause filters prune
-- candidates BEFORE the HNSW scan — critical for fast queries at 10M+
-- rows.
--
-- `embedding` is BGE-M3 dense output, 1024-dim, cosine-normalised by
-- the model itself. HNSW index below uses vector_cosine_ops.
-- `tsv` is the BM25 sparse representation, config-aware per language.
--
-- DEPENDS ON: 0014 (vector + unaccent extensions). This migration
-- will fail if those are not installed — apply in order.

CREATE TABLE IF NOT EXISTS speech_chunks (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    speech_id             UUID NOT NULL REFERENCES speeches(id) ON DELETE CASCADE,
    chunk_index           INTEGER NOT NULL,       -- 0..N-1 within parent speech
    text                  TEXT NOT NULL,
    token_count           INTEGER NOT NULL,       -- counted with BGE-M3 tokenizer, not char/word approximation
    char_start            INTEGER NOT NULL,       -- offset into speeches.text
    char_end              INTEGER NOT NULL,
    language              TEXT NOT NULL,

    -- Denormalised filter columns. Keep in sync with parent speech on
    -- updates; treat as derived state.
    politician_id         UUID,
    party_at_time         TEXT,
    level                 TEXT,
    province_territory    TEXT,
    spoken_at             TIMESTAMPTZ,
    session_id            UUID,

    -- Retrieval.
    embedding             vector(1024),           -- BGE-M3 dense; NULL until ingester's embed pass runs
    tsv                   tsvector,               -- BM25 lexical; generated by trigger on (language, text)
    tsv_config            TEXT,                   -- 'english' | 'french' | 'simple' (for IU/other)

    -- When the embedding was generated — lets the ingester re-embed
    -- stale chunks when we upgrade the model.
    embedded_at           TIMESTAMPTZ,
    embedding_model       TEXT,                   -- e.g. 'bge-m3-v1.5'

    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (speech_id, chunk_index)
);

-- HNSW on cosine distance. m/ef_construction are defaults; tune with
-- EXPLAIN ANALYZE against real traffic before touching.
CREATE INDEX IF NOT EXISTS idx_chunks_embedding
    ON speech_chunks USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- Lexical BM25.
CREATE INDEX IF NOT EXISTS idx_chunks_tsv ON speech_chunks USING gin (tsv);

-- Pre-filter indexes. Order matters: putting (level, province_territory)
-- first matches the dominant UI filter path.
CREATE INDEX IF NOT EXISTS idx_chunks_filters
    ON speech_chunks (level, province_territory, spoken_at DESC);
CREATE INDEX IF NOT EXISTS idx_chunks_politician
    ON speech_chunks (politician_id, spoken_at DESC) WHERE politician_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_chunks_needs_embedding
    ON speech_chunks (id) WHERE embedding IS NULL;
